Allow to use a wrapper when creating multiple translations
Astrotomic/laravel-translatable pull request #409
Opened 2024-05-07 11:00 UTC by artemiyone

**Description:**
Adding the ability to wrap multiple translations when creating new records.

**Changes:**
Added `translations_wrapper`   config to allow user to set a custom wrapper name.

**Purpose:**
When working with DTOs, we've found it useful to be able to wrap all the translations into a specific property when creating multiple records at once. 

**Benefits:**
Facilitates to create/convert the DTOs and use them for model creation/update.

**Usage:**
Developers can now set a custom wrapper for multiple creation and use it in the following way: 

You may define a wrapper property when creating new translations. Set the `translations_wrapper` property in translatable config file:
```php
'translations_wrapper' => 'translations',
```

Then just wrap multiple locales using that property:
```php
$data = [
  'author' => 'Gummibeer',
  'translations' => [
      'en' => ['title' => 'My first post'],
      'fr' => ['title' => 'Mon premier post'],
  ],
];
$post = Post::create($data);

echo $post->translate('fr')->title; // Mon premier post

2024-06-24 09:31 UTC, Gummibeer requested changes
Good MR - only very little adjustments needed. 🥳

2024-07-17 11:10 UTC, artemiyone commented on src/config/translatable.php
> +    | a separate model's property, just set it here.
Thanks :) !

2024-07-17 11:10 UTC, artemiyone commented on tests/TranslatableTest.php
> +        $this->app->make('config')->set('translatable.translations_wrapper', 'translations');
Done!

2024-07-17 11:11 UTC, artemiyone commented
Thanks for the feedback and sorry for the delay, busy days.

I've updated my PR and hopefully now is good to go :)

2024-08-26 16:02 UTC, Gummibeer approved these changes
Sorry for the delay! 😟 Toddlers aren't easy ... 🙈
Everything looking good and thanks for the changes! 🙏

2024-08-26 16:04 UTC, merged

2024-08-26 16:09 UTC, Gummibeer commented
https://github.com/Astrotomic/laravel-translatable/releases/tag/v11.15.0